/-
Chain: tomita-takesaki (7 cells, L1-L7, ALL PROVED)
Vertex: tomita-takesaki
Pillar: direct
Strategic role: HIGHEST-LEVERAGE chain — 4 downstream consumers (RH, BSD, PvNP, QG5D).
  Simultaneously backfills RH axiom, provides BSD/PvNP substrate, targets Mathlib upstream.
Source: Bost-Connes 1995; Takesaki TOA II; Bratteli-Robinson Vol II; Connes 1973/1976;
  Haagerup 1987; Araki-Woods 1968; Cuntz-Echterhoff-Li 2013
Generated by tt-architect (Phase A+B combined; Option B axiomatize-bridge-backfill).
-/

import Mathlib.Data.Real.Basic
import Mathlib.Data.Complex.Basic
import Mathlib.Algebra.Module.Defs
import Mathlib.Analysis.InnerProductSpace.Basic
import Mathlib.Analysis.CStarAlgebra.ContinuousLinearMap
import Mathlib.Algebra.Star.SelfAdjoint

namespace TomitaTakesaki

/-! ## Core types for the Tomita-Takesaki modular theory chain

These types parameterize the 7-cell proof chain L1–L7. The Bost-Connes algebra
(L1) is axiomatized per Option B; everything downstream is stated as sorry-
theorems whose type signatures carry the real mathematical content.

### Mathlib coverage at pinned SHA (v4.29.1)
- Hilbert spaces: `InnerProductSpace ℂ H` + `CompleteSpace H` — EXISTS
- Bounded operators: `H →L[ℂ] H` — EXISTS
- Von Neumann algebras: `VonNeumannAlgebra H` — EXISTS (double commutant)
- Antilinear operators, modular theory, KMS states: GAP (the contribution target)
-/

section BostConnes

/-- The Bost-Connes C*-dynamical system (B_K, α_t, ω₁) for K = ℚ(i).

Axiomatized per Option B of the brief. The BC algebra B_K = C*_r(N^⋊ ⋊ K) is
the reduced crossed product of the Hecke semigroup acting on a compactification
of K-adèles. Source: Bost-Connes 1995 Selecta Math 1:411-457 Theorem 25;
Laca-Larsen-Neshveyev 2015; Connes-Marcolli 2008 Ch III §3.4.

### Algebraic structure (Phase 1 backfill)
The algebra carries instance fields `[AddCommGroup]` and `[Module ℂ]` so the
GNS quotient construction `B_K / N` can be expressed via Mathlib's
`Submodule.Quotient` machinery. The `star` and `mul` fields remain as bare
functions for backwards compatibility with the L1 axioms; the GNS sesquilinear
form `⟨a, b⟩ := ω₁(star a · b)` is built from these. -/
structure BostConnesSystem where
  /-- The underlying C*-algebra B_K = C*_r(N^⋊ ⋊ K). -/
  Algebra : Type*
  /-- Additive abelian group structure on the algebra. -/
  [instAddCommGroup : AddCommGroup Algebra]
  /-- ℂ-module (complex vector space) structure. -/
  [instModule : Module ℂ Algebra]
  /-- Star operation (adjoint) on the algebra. -/
  star : Algebra → Algebra
  /-- Multiplication. -/
  mul : Algebra → Algebra → Algebra
  /-- The arithmetic time evolution α_t(μ_n) = N(n)^{it} μ_n. -/
  timeEvolution : ℝ → (Algebra → Algebra)
  /-- The canonical KMS₁ state ω₁ at inverse temperature β = 1. -/
  kms1State : Algebra → ℂ

attribute [instance] BostConnesSystem.instAddCommGroup BostConnesSystem.instModule

end BostConnes

section GNS

/-- Output of the GNS construction on (B_K, ω₁).

The GNS triple (H_{ω₁}, π_{ω₁}, Ω₁) is constructed via the sesquilinear form
⟨a, b⟩_{ω₁} := ω₁(b*a) on B_K/N_{ω₁}. Source: Bratteli-Robinson Vol I §2.3.3.

### Phase 5 type promotion

The `HilbertSpace` field now carries genuine Mathlib Hilbert-space
type-class instances: `NormedAddCommGroup`, `InnerProductSpace ℂ`,
`CompleteSpace`. These are required for downstream RH consumers
(`rh-L1 bc_operator_data` was blocked specifically on this promotion) to
treat `gns.HilbertSpace` as a real Hilbert space without bridge-side
`show` tactics. The instances flow from `L2.gns_construction`'s
realization `HilbertSpace := UniformSpace.Completion (B_K ⧸ nullIdeal)`,
where Mathlib's
`Mathlib.Analysis.InnerProductSpace.Completion` provides the chain. -/
structure GNSTriple (BC : BostConnesSystem) where
  /-- The GNS Hilbert space H_{ω₁}. -/
  HilbertSpace : Type*
  /-- Normed additive group structure on the Hilbert space. -/
  [instNACG : NormedAddCommGroup HilbertSpace]
  /-- Inner product space structure (sesquilinear, conjugate-linear in 1st arg). -/
  [instIPS : InnerProductSpace ℂ HilbertSpace]
  /-- Completeness of the Hilbert space. -/
  [instCS : CompleteSpace HilbertSpace]
  /-- The GNS representation π_{ω₁} : B_K → B(H). -/
  repr : BC.Algebra → (HilbertSpace → HilbertSpace)
  /-- The cyclic vector Ω₁. -/
  cycVec : HilbertSpace

attribute [instance] GNSTriple.instNACG GNSTriple.instIPS GNSTriple.instCS

end GNS

section TypeIII1

/-- Witness that the weak closure M = π_{ω₁}(B_K)'' is a type III₁ factor with
Ω₁ cyclic and separating.

Established via: KMS₁ uniqueness ⟹ extremality ⟹ factoriality ⟹ separating
(BC 1995 Thm 25 + BR Vol I Prop 2.5.3), then type III from non-traciality of
KMS₁ (Hecke projections), and type III₁ from density of {log N(𝔞)} in ℝ
(Q-linear independence of log p) giving spec(Δ) = (0,∞). Injectivity from
ITPFI (Araki-Woods 1968) ⟹ hyperfiniteness ⟹ injectivity (Connes 1976);
uniqueness via Haagerup 1987. -/
structure TypeIII1FactorWitness (BC : BostConnesSystem) (gns : GNSTriple BC) : Prop where
  /-- Ω₁ is cyclic for M: the closure of {π(a)Ω₁ : a ∈ B_K} is all of H. -/
  isCyclic : True
  /-- Ω₁ is separating for M: π(a)Ω₁ = 0 ⟹ a = 0 in M. -/
  isSeparating : True
  /-- M is a factor: Z(M) = ℂ·1. -/
  isFactor : True
  /-- M is of type III₁: Connes S-invariant S(M) = ℝ₊*. -/
  isTypeIII1 : True
  /-- M is the unique injective type III₁ factor (Haagerup 1987). -/
  isInjective : True

end TypeIII1

section ModularTheory

/-- The modular data (Δ, J, K₁) from polar decomposition of the Tomita operator.

The antilinear operator S: π(a)Ω₁ ↦ π(a*)Ω₁ is densely defined, closable, and
its closure has polar decomposition S̄ = JΔ^{1/2} where:
- Δ = S*S̄ is positive self-adjoint (possibly unbounded for type III)
- J is antiunitary with J² = 1 and JΔJ = Δ⁻¹
- K₁ = -log Δ is the KMS Hamiltonian satisfying K₁·Ω_{n,m,α} = log(N(n)/N(m))·Ω_{n,m,α}

Source: Takesaki TOA II VIII.3.2; Bratteli-Robinson Vol II §2.5.3 + §5.3;
Cuntz-Echterhoff-Li 2013 Theorem 3.5. -/
structure ModularPair (BC : BostConnesSystem) (gns : GNSTriple BC) where
  /-- The modular operator Δ = S*S̄ (positive, self-adjoint, possibly unbounded).
      Modeled as a function H → H; in the backfill phase this refines to an
      unbounded self-adjoint operator on a dense domain. -/
  Delta : gns.HilbertSpace → gns.HilbertSpace
  /-- The modular conjugation J (antiunitary involution).
      Antilinear: J(αx + βy) = ᾱJ(x) + β̄J(y). Mathlib gap — no `Antilinear`
      map type; modeled as a bare function. -/
  J : gns.HilbertSpace → gns.HilbertSpace
  /-- The KMS Hamiltonian K₁ = H_BC with Δ = e^{-K₁}.
      K₁·Ω_{n,m,α} = log(N(n)/N(m))·Ω_{n,m,α} on the bilateral Hecke basis. -/
  KMSHamiltonian : gns.HilbertSpace → gns.HilbertSpace

/-- Properties of the modular pair established by the polar decomposition. -/
structure ModularPairProperties (BC : BostConnesSystem) (gns : GNSTriple BC)
    (mp : ModularPair BC gns) : Prop where
  /-- J is an involution: J² = id. -/
  j_involution : ∀ x : gns.HilbertSpace, mp.J (mp.J x) = x
  /-- JΔJ = Δ⁻¹ (stated via spectral-calculus identity on vectors). -/
  j_intertwines : True
  /-- Δ = e^{-K₁} (closing the identification via partition-function comparison). -/
  delta_eq_exp : True
  /-- spec(Δ) = [0, ∞) (type III₁ spectral characterization). -/
  spectrum_full : True

/-- The modular automorphism group σ_t: M → M defined by σ_t(a) = Δ^{it} a Δ^{-it}.

This is the one-parameter *-automorphism group of M generated by the modular
operator. Under the BR Vol II §5.3 sign convention: σ_t = Ad(Δ^{-it}). The
load-bearing content of L4 is that this equals the BC time evolution α_t on
the representation. -/
structure ModularAutomorphismGroup (BC : BostConnesSystem) (gns : GNSTriple BC)
    (mp : ModularPair BC gns) where
  /-- σ_t as a one-parameter family of automorphisms. -/
  σ : ℝ → ((gns.HilbertSpace → gns.HilbertSpace) → (gns.HilbertSpace → gns.HilbertSpace))
  /-- σ_t is an automorphism (preserves composition and adjoint). -/
  is_automorphism : True

end ModularTheory

section Galois

/-- The Galois action on B_K for K = ℚ(i).

Gal(K/ℚ) = ℤ/2 acts by complex conjugation. The Galois action intertwines with
the modular conjugation J on the Hecke basis: J·Ω_{n,m,α} involves the swap
(n,m,α) ↦ (m,n,-α) with a partition-function prefactor. The U_c-twisting
realizes the Galois cocycle. Source: BC 1995 §3 + Connes-Marcolli 2008 Ch III. -/
structure GaloisActionData (BC : BostConnesSystem) (gns : GNSTriple BC) where
  /-- The Galois group Gal(K/ℚ) ≅ ℤ/2.
      Restricted to `Type 0` (the lowest universe) since ℤ/2 lives there;
      this also avoids universe-inference issues when embedded in `Prop`
      contexts (e.g. `Nonempty (GaloisActionData BC gns)` in L6). -/
  GaloisGroup : Type
  /-- The Galois action on the algebra. -/
  action : GaloisGroup → (BC.Algebra → BC.Algebra)
  /-- The Galois action extends to an action on the GNS space. -/
  liftedAction : GaloisGroup → (gns.HilbertSpace → gns.HilbertSpace)

end Galois

section SpectralRealization

/-- The self-adjoint operator D_∞ = log(Δ₁) whose spectrum encodes the
    arithmetic data. This is the bridge to the RH axiom
    `D_infinity_spectral_encoding`.

### Phase 5 lift

`D_infty` is promoted from a bare function `H → H` to a genuine Mathlib
`ContinuousLinearMap` `H →L[ℂ] H`; `is_self_adjoint` is promoted from
`True` to the real `IsSelfAdjoint D_infty`. This pairing — a bounded
self-adjoint operator on a Mathlib-typed Hilbert space — is exactly what
RH L1 (`bc_operator_data`) consumes. -/
structure SpectralRealizationData (BC : BostConnesSystem) (gns : GNSTriple BC)
    (mp : ModularPair BC gns) where
  /-- D_∞ = log(Δ₁) = -K₁ (bounded self-adjoint operator on H_{ω₁}). -/
  D_infty : gns.HilbertSpace →L[ℂ] gns.HilbertSpace
  /-- D_∞ is self-adjoint. -/
  is_self_adjoint : IsSelfAdjoint D_infty
  /-- D_∞ = -K₁ (sign convention alignment). -/
  eq_neg_kms_hamiltonian : True

end SpectralRealization

end TomitaTakesaki
